version: '3.3'
services:
  coco-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'coco'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'cococtnr'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'cocopass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admpassword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 23306:3306
    expose:
      # Opens port 3306 on the containers
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql

# svolumes:
#  my-db:
